export const variables = {
  navbarBottomHeight: {
    iOS: 80,
    android: 78,
  },
  borderRadius: {
    min: 6,
    small: 12,
    medium: 24,
    base: 30,
  },
  //TODO - unify colors thing
  colors: {
    profileImageBorder: '#999',
    profileImageBg: '#d3d3d3',
    accentGreen: '#499e55',
    accentRed: '#ea3336',
    black: '#000000',
    black30: '#f8f8f8',
    blue: '#1F5A8F',
    destructiveRed: '#c21114',
    inputBorder: '#c4c4c6',
    lightBlue: '#7AC1FF',
    orange_primary: '#ffc73f',
    overlayBlack: '#00000055',
    overlayHeaderBg: '#f9f9f9',
    chatBubble: '#f2f2f2',
    chatBubbleDate: '#f6f6f6',
    overlayHeaderBorder: '#b2b2b2',
    pinkishGrey: '#c6c6c6',
    steel: '#8a8a8e',
    pale: '#ffedc6',
    watermelon: '#ff386a',
    menuBg: '#e6e6e6',
    tabsBackground: '#e4e4e4',
    toggleOff: '#ccc',
    transparent: 'transparent',
    white: '#ffffff',
    whiteTwo: '#f5f5f5',
  },
  container: {
    verticalPaddingBase: 40,
  },
  fontSize: {
    min: 12,
    small: 16,
    base: 17,
    medium: 18,
    bigger: 20,
    big: 26,
    large: 32,
    xLarge: 48,
  },
  lineHeight: {
    base: 21,
    bigger: 24,
    heading: 28,
    large: 32,
  },
  letterSpacing: { base: 0.29 },
  spacing: {
    min: 4,
    small: 8,
    base: 12,
    medium: 16,
    big: 24,
    large: 32,
    xLarge: 64,
    xxLarge: 128,
  },
};
