export const LOG_IN_USER = 'LOGIN/LOG_IN_USER';
export const LOG_OUT_USER = 'LOGIN/LOG_OUT_USER';
export const SET_USER_TOKEN = 'LOGIN/SET_USER_TOKEN';
export const SET_USER_LOGIN = 'LOGIN/SET_USER_LOGIN';
export const SET_SELECTED_NOTIFICATION_CATEGORIES = 'LOGIN/SET_SELECTED_NOTIFICATION_CATEGORIES';
