export const SET_OFFERS_DATA = 'OFFERS/SET_OFFERS_DATA';
export const ADD_OFFERS_DATA = 'OFFERS/ADD_OFFERS_DATA';
export const SET_CURRENT_OFFER_DATA = 'OFFERS/SET_CURRENT_OFFER_DATA';
export const UPDATE_CURRENT_OFFER_IMAGES = 'OFFERS/UPDATE_CURRENT_OFFER_IMAGES';
export const UPDATE_OFFER_IMAGES_BY_OFFER_SLUG = 'OFFERS/UPDATE_OFFER_IMAGES_BY_OFFER_SLUG';
export const ADD_IMAGE_TO_CURRENT_OFFER = 'OFFERS/ADD_IMAGE_TO_CURRENT_OFFER';
export const ADD_OFFER_IMAGE_TO_OFFERS_LIST_BY_OFFER_SLUG = 'OFFERS/ADD_OFFER_IMAGE_TO_OFFERS_LIST_BY_OFFER_SLUG';
export const SET_CURRENT_OFFER_COMPANY_DETAIL = 'OFFERS/SET_CURRENT_OFFER_COMPANY_DETAIL';
