export const SET_USER_DATA = 'USER/SET_USER_DATA';
export const SET_USER_STATUS_DATA = 'USER/SET_USER_STATUS_DATA';
export const SET_STATUS = 'USER/SET_STATUS';
export const SET_THREAD_LIST_DATA = 'USER/SET_THREAD_LIST_DATA';
export const UPDATE_THREAD_LIST = 'USER/UPDATE_THREAD_LIST';
export const SET_PROFILE_DATA = 'USER/SET_PROFILE_DATA';
