
const SETTINGS_GET_SESSION_TOKEN = '/token/session';
const SETTINGS_GET_TRANSLATIONS = '/translations';
const SETTINGS_GET_ESHOP_SETTINGS = '/settings';
const SETTINGS_POST_CURRENCY_CHANGE = '/currency'
const SETTINGS_GET_PHONE_PREFIXES = '/phone-prefix'
const SETTINGS_GET_COUNTRIES = '/countries';


export {
  SETTINGS_GET_SESSION_TOKEN,
  SETTINGS_GET_TRANSLATIONS,
  SETTINGS_GET_ESHOP_SETTINGS,
  SETTINGS_POST_CURRENCY_CHANGE,
  SETTINGS_GET_PHONE_PREFIXES,
  SETTINGS_GET_COUNTRIES,
};
